### ISSUE TITLE
Allowing args to be passed and handling environment variables

### ISSUE THREAD

**Issue by dantman** [zkochan/zx#2]
I really wanted to be able to pass arguments in to `zx` commands (I wanted to simplify the first half of some common `sequelize` commands I use).

This just wouldn't work within commander so I made some major changes that uses a combination of yargs and manual handling to implement that. Along with including some other fixes.

https://github.com/dantman/zx/commit/e8778b0f75647903395d7e2343c476788f8dc3c6

---

However sadly I discovered this doesn't actually fully help me. I actually want to simplify `OTAKU_CONFIG=../local/config.json sequelize model:create` to `zx model ...`.

`exec-cmds` doesn't use a shell and doesn't have a way to pass env information. So I can't setup any alternatives like including env info into the config:

``` yaml
foo:
  env:
    FOO_BAR: baz
  command: foo_run
```

**Comment by zkochan** [comment]
Do you want to achieve something similar to hapi's [confidence](https://github.com/hapijs/confidence)?

**Comment by zkochan** [comment]
You can assign values to environment variables in NodeJS, so it's possible to add this feature to `zx`.

``` js
process.env.FOO_BAR = 'baz';
```

Your yml example reminds me [docker-compose](https://docs.docker.com/compose/compose-file/) :)

**Comment by zkochan** [comment]
But wait, can't you just write 2 commands?

Instead of this:

``` yml
foo:
  env:
    FOO_BAR: baz
  command: foo_run
```

You should be able to write this

``` yml
foo:
  - "SET FOO_BAR = baz"
  - foo_run
```

**Comment by dantman** [comment]
confidence looks overboard and not really what I was thinking. All I wanted with that idea was a way for a command to specify environment variables.

I worked around that for now by using `env`.

``` yaml
sequelize: env OTAKU_CONFIG=../local/config.json sequelize
migrate: zx sequelize db:migrate
migration: zx sequelize migration:create
model: zx sequelize model:create
```
